version: "3.9"

services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data

  web:
    image: nginx:1.20-alpine
    ports:
      - 8081:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data  
  
  db:
    build: ./infra/mysql
    container_name: "laravel-product"
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33307:3306
    environment:
      MYSQL_DATABASE: laravel-product-db
      MYSQL_USER: product-user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Tokyo

volumes:
  db-store:
  php-fpm-socket: